// Tooltip help text for each Meta report column — shown via CircleAlert icon in column headers
import type { MetaColumnKey } from './meta-types';

export const META_COLUMN_HELP: Partial<Record<MetaColumnKey, string>> = {
  action: 'Bat hoac tat nhanh trang thai phan phoi cua campaign, ad set hoac ad.',
  entity: 'Ten doi tuong dang duoc hien thi trong bang. Tuy theo tang hien tai se la Campaign, Ad Set hoac Ad.',
  status: 'Trang thai van hanh hien tai cua doi tuong tren Meta nhu Active, Paused, Draft hoac Error.',
  account: 'Tai khoan quang cao Meta dang so huu va phan phoi doi tuong nay.',
  createdAt: 'Thoi diem campaign duoc tao. Ad set va ad co the khong co du lieu tao trong mock hien tai.',
  bidStrategy: 'Chien luoc dau gia Meta dang ap dung de toi uu phan phoi cho muc tieu da chon.',
  budget: 'Ngan sach duoc cap cho campaign hoac ad set trong chu ky van hanh.',
  amountSpent: 'Tong chi tieu da ghi nhan trong khoang thoi gian dang xem.',
  resultRoas: 'Ty le doanh thu tren chi tieu quang cao. Gia tri cao hon thuong tot hon.',
  appInstalls: 'So luot cai dat app duoc quy ve cho doi tuong nay.',
  costPerAppInstall: 'Chi phi trung binh de tao ra mot luot cai dat app.',
  cpm: 'Chi phi trung binh cho moi 1.000 lan hien thi.',
  results: 'Tong so ket qua chinh theo muc tieu toi uu hien tai. Trong mock nay dang map voi installs.',
  costPerResults: 'Chi phi trung binh cho moi ket qua chinh duoc ghi nhan.',
  ctrAll: 'Ty le nhap chuot tren tong so lan hien thi, tinh tren tat ca click.',
  cpcAll: 'Chi phi trung binh cho moi click, tinh tren tat ca click.',
  cvrInstall: 'Ty le chuyen doi tu click thanh install.',
  ctrInstall: 'Ty le install tren tong so impression.',
  costPerLead: 'Chi phi trung binh de tao ra mot lead.',
  leads: 'Tong so lead ghi nhan duoc tu doi tuong nay.',
  cvrLeads: 'Ty le chuyen doi tu click thanh lead.',
  impression: 'Tong so lan quang cao duoc hien thi.',
  reach: 'Tong so nguoi dung duy nhat da nhin thay quang cao.',
  frequency: 'So lan hien thi trung binh tren moi nguoi da duoc reach.',
  completedRegistration: 'So luot dang ky hoan tat sau khi nguoi dung tuong tac voi quang cao.',
  costPerCompletedRegistration: 'Chi phi trung binh cho moi luot dang ky hoan tat.',
  purchase: 'So luot mua hang hoac giao dich mua duoc ghi nhan.',
  costPerPurchase: 'Chi phi trung binh de tao ra mot purchase.',
  linkClicks: 'So click vao lien ket dich den.',
  cpcLinkClick: 'Chi phi trung binh cho moi click vao lien ket dich den.',
};
